### PR TITLE
Added a tryWriteChan function for non-blocking writes to channels.

### PR DESCRIPTION
**Pull request by polendri**
My first Haskell contribution so I don't know if style is up to par, but I needed this for a personal project, and I thought maybe it could be of use in the mainline? It adds the notion of dropping elements if the channel is full. It doesn't make sense for unbounded channels, but Control.Concurrent.MVar has these "try" functions, so I think it belongs.

I feel dirty not adding corresponding tests, but there's no test framework in place and not everything is covered to begin with.

### CODE REVIEW

**Comment by acw** [comment]
Thanks! It looks good to me, except for one thing: it's not really non-blocking, because it'll still block on access to the channel itself (i.e., modifyMVar_). I'm happy to take the change, though, as it seems like a useful capability, but we should perhaps change the documentation on them do make it clear that it could still block?

**Comment by polendri** [comment]
Ah shoot, good point. I'll add a revision to change that to something along the lines of "does not block if the channel is full" and "does not block if the channel is empty". One would definitely still want such functions to block on the read or write MVar.

**Comment by polendri** [comment]
I updated the comments and squashed it into one commit; let me know what you think.

**Comment by acw** [comment]
Perfect! It's merged. I'll bump the version number and push it to GitHub shortly.

**Comment by polendri** [comment]
I see the version bump from 8 days ago, but no merge yet? No hurry, just making sure it wasn't forgotten.

**Comment by acw** [comment]
Hrm. It looks like the merge b0rked somewhere in the process. Let me try this again ...

**Comment by acw** [comment]
OK. Should be in and up on Hackage now. Sorry for the delay; I must have missed the confirm button last time.

**Pull request merged**
